# Main text of home
title: Cristiano Fraga Guimarães Nunes
# bio: Computer Engineer, Researcher

# Summary info
description: A blog about technology

# If it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

url: https://cfgnunes.github.io

# Define default permalink for all pages if it was not set
permalink: /:title/

# To enable google analytics, supply your token below
analytics-google: "UA-137055954-1"

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# If you don't want comments in your posts, leave categories empty
disqus:
  shortname: cfgnunes # enter this from your disqus account
  categories: [blog, project] # only show disqus for posts that have these categories

# If you don't have any of social below, comment the line
email: cfgnunes@gmail.com
# facebook: cristianofraganunes
github: cfgnunes
#instagram: cfgnunes
lattes: 3985172295525735
# pinterest: mypinterest
linkedin: cfgnunes
researchgate: Cristiano_Nunes3
scholar: nrrROToAAAAJ
# skoob: 3647026
# spotify: cfgnunes
# twitter: cfgnunes
# youtube: cfgnunes
# gitlab: mygitlab
# medium: medium
# quora: userquora
# reddit: username
# stackoverflow: 3112437/cristiano-nunes
social-links-order:
  [
    linkedin,
    lattes,
    github,
    researchgate,
    scholar,
    gitlab,
    stackoverflow,
    instagram,
    twitter,
    facebook,
    youtube,
    spotify,
    skoob,
    quora,
    reddit,
    medium,
    email,
  ]

authors:
  cfgnunes:
    name: Cristiano Nunes
    external-image: false
    picture: assets/images/profile.jpg
    twitter: cfgnunes
    bio: A warrior of the light.

# Do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 760px
width: large

# If you do/don't need pagination, toggle 'enabled' between true/false below
pagination:
  enabled: false
  sort_reverse: true # Display recent posts first
  title: ":title" # Changing this will mess up the header display logic
  per_page: 5
  permalink: "/:num/" # Pagination link that will be appended

# Enable or disable the pages
blog: true
projects: false
about: true

# Show the "read time" of the posts
read-time: true

# Show the "tags" inside the posts
show-tags: true

# Show related posts inside a post
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# Show author block at the end of a post
show-author: true

# Enable animations
animation: true

# Add default values to specific pages or layouts
defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      layout: "post"
    values:
      # Setting all post to not hidden by default,
      # can be overridden in the front matter for a specific post
      hidden: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
  - jekyll-paginate-v2

jekyll-mentions:
  base_url: https://github.com

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
  ".github",
  "Gemfile.lock",
  "Gemfile",
  "makefile",
  "README.md",
  "vendor/bundle"
  ]
